#!/usr/bin/env python3
"""
Vulnerability Reporter — CVE / CNVD Report Generator
======================================================
Generate standardized vulnerability reports for submission to:
- CVE (Common Vulnerabilities and Exposures) via MITRE / NVD
- CNVD (China National Vulnerability Database) via CNCERT
- CNNVD (China National Vulnerability Database of Information Security)
- Security vendors (via responsible disclosure)

Usage:
  python3 vuln_reporter.py list                          # List all findings
  python3 vuln_reporter.py generate --id <finding_id>    # Generate CVE report
  python3 vuln_reporter.py generate --id <id> --format cnvd  # CNVD format
  python3 vuln_reporter.py export --all                   # Export all as markdown
"""

import json, os, sys, argparse
from pathlib import Path
from datetime import datetime, timezone

VULN_DB = Path.home() / ".openclaw" / "vuln_findings.json"
REPORTS_DIR = Path.home() / ".openclaw" / "vuln_reports"

CVSS_SCORES = {
    "CRITICAL": "9.0-10.0",
    "HIGH": "7.0-8.9",
    "MEDIUM": "4.0-6.9",
    "LOW": "0.1-3.9",
    "INFO": "0.0"
}

def load_findings():
    if not VULN_DB.exists():
        return []
    with open(VULN_DB) as f:
        db = json.load(f)
    all_findings = []
    for scan in db.get("scans", []):
        for f in scan.get("findings", []):
            f["scan_date"] = scan.get("timestamp", "?")
            all_findings.append(f)
    return all_findings

def generate_cve(finding: dict) -> str:
    """Generate CVE-style report."""
    sev = finding.get("severity", "MEDIUM")
    cvss_range = CVSS_SCORES.get(sev, "?")
    
    report = f"""# CVE Report

## Vulnerability Summary

- **Title:** {finding.get('vulnerability', 'Unknown')}
- **Severity:** {sev} (CVSS {cvss_range})
- **Date Discovered:** {finding.get('scan_date', '?')[:10]}
- **CVE ID:** [PENDING]

## Affected Component

- **Type:** {finding.get('type', 'Unknown')}
- **File/URL:** {finding.get('file', finding.get('url', finding.get('host', 'N/A')))}
{f"- **Line:** {finding.get('line', 'N/A')}" if finding.get('line') else ""}
{f"- **Package:** {finding.get('package', 'N/A')}" if finding.get('package') else ""}

## Description

{finding.get('description', finding.get('detail', finding.get('finding', 'No description')))}

{f"**Vulnerable Code:** `{finding.get('match', 'N/A')}`" if finding.get('match') else ""}

## Impact

{sev} severity vulnerability. 
{f"Could lead to information disclosure, unauthorized access, or system compromise." if sev in ('CRITICAL','HIGH') else "Limited impact."}

## Remediation

{finding.get('fix', 'Apply security best practices for this vulnerability type.')}

## References

- OWASP Top 10: https://owasp.org/www-project-top-ten/
- CWE: https://cwe.mitre.org/

---
*Generated by OpenClaw Security Scanner | {datetime.now().strftime('%Y-%m-%d')}*
"""
    return report

def generate_cnvd(finding: dict) -> str:
    """Generate CNVD (China National Vulnerability Database) format report."""
    sev_map = {"CRITICAL": "高危", "HIGH": "高危", "MEDIUM": "中危", "LOW": "低危", "INFO": "信息"}
    
    report = f"""# CNVD 漏洞报告

## 基本信息

| 项目 | 内容 |
|------|------|
| **漏洞名称** | {finding.get('vulnerability', 'Unknown')} |
| **危害等级** | {sev_map.get(finding.get('severity', 'MEDIUM'), '中危')} |
| **发现日期** | {finding.get('scan_date', '?')[:10]} |
| **CNVD编号** | [待分配] |

## 影响组件

- **类型:** {finding.get('type', 'Unknown')}
- **路径:** {finding.get('file', finding.get('url', finding.get('host', 'N/A')))}
{f"- **行号:** {finding.get('line', 'N/A')}" if finding.get('line') else ""}
{f"- **软件包:** {finding.get('package', 'N/A')}" if finding.get('package') else ""}

## 漏洞描述

{finding.get('description', finding.get('detail', finding.get('finding', '无详细描述')))}

## 验证代码

```
{finding.get('match', finding.get('payload', 'N/A'))}
```

## 修复建议

{finding.get('fix', '请参考OWASP相关安全指南进行修复。')}

## 参考

- OWASP Top 10: https://owasp.org/www-project-top-ten/
- CNCERT: https://www.cert.org.cn/
- CNVD: https://www.cnvd.org.cn/

---
*由 OpenClaw Security Scanner 生成 | {datetime.now().strftime('%Y-%m-%d')}*
"""
    return report

def cmd_list(args=None):
    findings = load_findings()
    if not findings:
        print("No findings yet. Run security_scanner.py first.")
        return
    
    print(f"\n📋 Vulnerability Database ({len(findings)} findings)\n")
    for i, f in enumerate(findings):
        sev = f.get("severity", "?")
        icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}.get(sev, "❓")
        print(f"  [{i}] {icon} {sev:<8} {f.get('vulnerability', '?')}")
        loc = f.get('file', f.get('url', f.get('host', '')))
        if loc: print(f"       {loc}")

def cmd_generate(args):
    findings = load_findings()
    try:
        idx = int(args.id)
        finding = findings[idx]
    except (ValueError, IndexError):
        print(f"Invalid finding ID: {args.id}. Use 'list' to see IDs.")
        return
    
    fmt = args.format or "cve"
    if fmt == "cve":
        report = generate_cve(finding)
    elif fmt == "cnvd":
        report = generate_cnvd(finding)
    else:
        print(f"Unknown format: {fmt}")
        return
    
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"vuln_{finding.get('scan_date','?')[:10]}_{finding.get('vulnerability','unknown')[:30].replace(' ','_')}_{fmt}.md"
    filepath = REPORTS_DIR / filename
    
    with open(filepath, "w") as f:
        f.write(report)
    
    print(f"✅ Report saved: {filepath}")
    print(report[:500])

def cmd_export(args):
    findings = load_findings()
    if not findings:
        print("No findings.")
        return
    
    md = f"# Vulnerability Report — {datetime.now().strftime('%Y-%m-%d')}\n\n"
    md += f"**Total:** {len(findings)} findings\n\n"
    
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        sev_findings = [f for f in findings if f.get("severity") == sev]
        if not sev_findings: continue
        md += f"## {sev} ({len(sev_findings)})\n\n"
        for f in sev_findings:
            md += f"- **{f.get('vulnerability','?')}** — {f.get('file', f.get('url', f.get('host','?')))}\n"
            md += f"  - {f.get('description', f.get('detail',''))}\n"
            md += f"  - Fix: {f.get('fix','N/A')}\n\n"
    
    filepath = REPORTS_DIR / f"vuln_export_{datetime.now().strftime('%Y%m%d')}.md"
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w") as f:
        f.write(md)
    print(f"✅ Export saved: {filepath}")

def main():
    parser = argparse.ArgumentParser(description="Vulnerability Reporter")
    sub = parser.add_subparsers(dest="cmd")
    
    sub.add_parser("list", help="List all findings")
    gen = sub.add_parser("generate", help="Generate CVE/CNVD report")
    gen.add_argument("--id", required=True)
    gen.add_argument("--format", choices=["cve", "cnvd"])
    sub.add_parser("export", help="Export all as markdown").add_argument("--all", action="store_true")
    
    args = parser.parse_args()
    {"list": cmd_list, "generate": cmd_generate, "export": cmd_export}[args.cmd](args)

if __name__ == "__main__":
    main()
